env:
  global:
    secure: LKh9LZrsrUaZ42Rp5A+PqL7xYvQqDb1Ikg7Xoii9Zk5FYCDTZLFXyoRd5R1eHo+Kska1nXLFyxMwPxyrOaZWsXkEor0uhki82RdcmMZp/JhgGY5f2y9/Qk5ldKMrcr7LhNZhMkS4FYnYcHKcKsKPbz3SknL5UITcTy1fImm8gwxRf0mGKvqYYqVou82eMAqf6p/IRzmpbwshLLgHlbT5yKdLogfT6xSyjypjZrZ2d2ZVxo+xtiMOOJGRWn6ojAyvToMaAUqoyZ3ZRB5L75dzDADyYGV/Yy6M1S2TS5XcJzPPcFVI1IFRa3jmJlUpd33LxpuSm9hJKkY2WrYsd5c4WVqZm/cenGiktRozu31mJUDM05L/rXQAp3ayZQiImzmgUImERDX4qYd4B1ZT3OjSZaKV9F/JkPfnohMU7ilbTNL62/RQKyY2+pQbVWXSApPadTReoQilVjOrQdJxVMztVjYdTwwaKzMG18ahfmT6fDv00lTo++JhszGkNeCr7ukF0exsj5/m/PijnZaD0Xa4L+R3GcPnHEFSXIdKgvci7c/25erlExQbD1LwSfrcjA0rvY5asSAMlEuLAY6vnL17RcgyIZKQVWOhYagPhXFNZH8h05V2rRI3PinjVjYFKx+TRbARaC1TXSSAoi96hdlnI3FRrmXzYISy3iqgiG5LzCo=
after_success:
  - $(npm bin)/set-up-ssh --key "${encrypted_f8a826b60c9b_key}"
      --iv "${encrypted_f8a826b60c9b_iv}"
      --path-encrypted-key .travis-github-deploy-key.enc
  - $(npm bin)/update-branch --commands 'npm run build && touch dest/.nojekyll'
      --commit-message "Update gh-pages @ ${TRAVIS_COMMIT}"
      --directory 'dest'
      --distribution-branch 'gh-pages'
      --source-branch 'master'
language: node_js
git:
  depth: 1
